// Generated by CoffeeScript 1.3.3

KISSY.add("util/suitableimage", function(S) {
  var $, DOM, SuitableImage, defaultConfig;
  $ = S.all;
  DOM = S.DOM;
  defaultConfig = {
    wrapperEl: null,
    image: null,
    width: null,
    height: null,
    cover: true,
    contain: false,
    lazyload: true,
    position: null,
    relative: false,
    showDura: 0.5,
    showFunc: "easeBoth",
    loadingPic: null,
    autoResize: true
  };
  SuitableImage = (function() {

    function SuitableImage(config) {
      var height, pic, width, wrapperEl,
        _this = this;
      if (typeof config === "string") {
        config = {
          wrapperEl: config
        };
      } else if (config.length != null) {
        config = {
          wrapperEl: config
        };
      }
      this.config = S.merge(defaultConfig, config);
      wrapperEl = this.config.wrapperEl = $(this.config.wrapperEl);
      if (!(this.config.image != null)) {
        this.config.image = wrapperEl.attr('data-ks-simage') || wrapperEl.attr('data-image') || wrapperEl.one('img').attr('src');
      }
      if (!(this.config.image != null)) {
        return;
      }
      this.width = width = !this.config.width ? wrapperEl.width() : this.config.width;
      this.height = height = !this.config.height ? wrapperEl.height() : this.config.height;
      if (!this.config.lazyload) {
        $(wrapperEl).append(DOM.create("<div style=\"width:100%;height:100%;background:url(" + this.config.image + ");\"></div>"));
      } else {
        if (this.config.loadingPic) {
          wrapperEl.css("background", "url(" + this.config.loadingPic + ") center no-repeat");
        }
        this.config.pic = pic = new Image();
        $(pic).css("opacity", 0);
        pic.onload = function() {
          return _this._load(pic, width, height);
        };
        this.src = pic.src = this.config.image;
        this._size(pic, width, height);
      }
      if (this.config.autoResize && (this.config.cover || this.config.contain)) {
        $(window).on("resize", function() {
          var s_height, s_width;
          _this.width = s_width = !_this.config.width ? wrapperEl.width() : _this.config.width;
          _this.height = s_height = !_this.config.height ? wrapperEl.height() : _this.config.height;
          if (!(s_width === width && s_height === height)) {
            return _this.resize(s_width, s_height);
          }
        });
      }
    }

    SuitableImage.prototype._load = function(pic, width, height) {
      var inner,
        _this = this;
      if (this.config.cover || this.config.contain) {
        inner = this._size(pic, width, height);
      } else {
        inner = DOM.create("<div style=\"width:100%;height:100%;background:url(" + pic.src + ");\"></div>");
        $(inner).css("opacity", 0);
      }
      return $(inner).appendTo(this.config.wrapperEl).animate({
        'opacity': 1
      }, this.config.showDura, this.config.showFunc, function() {
        return _this.config.wrapperEl.css("background", "none");
      });
    };

    SuitableImage.prototype._size = function(pic, width, height) {
      var inner;
      if (!pic.width || !pic.height) {
        return;
      }
      inner = null;
      if (document.body.style.backgroundSize != null) {
        if (!this.config.relative) {
          this.config.wrapperEl.css("position", "relative");
        }
        inner = DOM.create("<span class='suitable-image-div' style='display: block'></span>");
        $(inner).css({
          "background": "url(" + pic.src + ") " + (this.config.position ? this.config.position : "center" + " no-repeat"),
          "background-size": this.config.contain ? "contain" : "cover",
          "width": "100%",
          "height": "100%",
          "opacity": 0,
          "position": this.config.relative ? "relative" : "absolute",
          "top": 0,
          "left": 0
        });
      } else {
        inner = this._sizeForLoser(pic, width, height);
      }
      return inner;
    };

    SuitableImage.prototype._sizeForLoser = function(pic, width, height) {
      var picHeight, picWidth, s_height, s_left, s_top, s_width, scale, _ref;
      if (!pic.width || !pic.height) {
        return;
      }
      _ref = [pic.width, pic.height], picWidth = _ref[0], picHeight = _ref[1];
      scale = width / picWidth;
      if (picHeight * scale >= height && !this.config.contain) {
        s_width = width;
        s_height = picHeight * scale;
        s_top = (s_height - height) / 2;
      } else {
        s_height = height;
        s_width = height / picHeight * picWidth;
        s_left = (s_width - width) / 2;
      }
      $(pic).css({
        top: s_top && !this.config.contain ? -s_top : 0,
        left: s_left && !this.config.contain ? -s_left : 0,
        width: s_width,
        height: s_height,
        position: 'absolute',
        opacity: 0,
        display: 'block',
        zoom: 1
      });
      return pic;
    };

    SuitableImage.prototype.resize = function(width, height) {
      if (this.config.cover || this.config.contain) {
        this._sizeForLoser(this.config.pic, width, height);
      }
      return this;
    };

    return SuitableImage;

  })();
  S.namespace("Util");
  return S.Util.suitableImage = SuitableImage;
});
